services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: replace_in_production_please
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
